### ISSUE TITLE
Java.IO.FileNotFoundException (PCL project)

### ISSUE THREAD

**Issue by Splinterjke** [jcphlux/XamarinAudioManager#13]
Xamarin   4.3.0.636
Xamarin.Android   7.1.0.34
Xamarin.iOS   10.4.0.114
PCL xamarin.forms project. Plugin is referenced in each target platform (iOS and Android).
I've created 'Sounds' folder in each platform and put *.mp3 file. Initializer.Initialize() is called. PlaySound is called in some command like this:
`await AudioManager.Audio.Manager.PlaySound("sound.mp3");`
Build action property for mp3 files is 'Content' and 'Do not Copy'...
So i get that Exception when tryin to call PlaySound. Any idea what's wrong?

**Comment by denis-reichelt** [comment]
@Splinterjke 
In Android, try to place the mp3 file under the Assets folder: Assets/Sounds/sound.mp3
Set the Build action to "AndroidAsset". Now the file should be found.

**Comment by Splinterjke** [comment]
@denis-reichelt Thank you. The issue is solved.

**Comment by jcphlux** [comment]
@denis-reichelt you are very helpful to have around 🥇
