### ISSUE TITLE
java.io.FileNotFoundException: Sounds/siren.mp3

### ISSUE THREAD

**Issue by kikolopes90** [jcphlux/XamarinAudioManager#7]
I do not understand anything, I use Xamarin Forms PCL.
Where can I put music to android and ios?

**Comment by kikolopes90** [comment]
Does not support Xamarin Forms PCL?

**Comment by jcphlux** [comment]
In the demo project I put the mp3's in a shared location and just link the file in each projects.
[Click here for more info on file linking.](https://msdn.microsoft.com/en-us/library/9f4t9t92(v=vs.100).aspx#Anchor_0)

For android the default folder is [XamarinAndroidProject]\Assets\Sounds\siren.mp3 
and for iOs the defalut folder is [XamariniOSProject]\Sounds\siren.mp3

In Andround mark the files Build Action as AndroidAsset 
and in iOS mar the Build Action as Content.

**Comment by jcphlux** [comment]
I currently have not figure out a way to embed the audio file in the PCL. You will need to add a ref to the audio file in each project platform.

**Comment by kikolopes90** [comment]
It works, thank you.

SoundPath = "Sounds" does not work, I do not know why, I changed to "sounds" (lowercase) so I already work

**Comment by jcphlux** [comment]
The case will match the case of the folder you create in the project. Glad you are working. I will Add details in the usage on customizing the install folder.
